# wallust.toml needs to include this
# alacritty = { template = 'alacritty.toml', target = '~/.config/alacritty/colors.toml' }
# and alacritty.toml should import that file under [general]
[colors.primary]
background = "#030305"
foreground = "#FFC37E"

[colors.normal]
black   = "#040608"
red     = "#FFFFFF"
green   = "#7F7871"
yellow  = "#5B7E9E"
blue    = "#8A9075"
magenta = "#A78A93"
cyan    = "#E39554"
white   = "#FFB873"

[colors.bright]
black   = "#BB7436"
red     = "#434858"
green   = "#7F7871"
yellow  = "#5B7E9E"
blue    = "#8A9075"
magenta = "#A78A93"
cyan    = "#E39554"
white   = "#F7D3B1"

