config:
  backup: true
  banner: true
  create: true
  dotpath: .
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  d_waybar:
    src: config/waybar
    dst: ~/.config/waybar
  d_dunst:
    src: config/dunst
    dst: ~/.config/dunst
  d_hypr:
    src: config/hypr
    dst: ~/.config/hypr
  d_wallust:
    src: config/wallust
    dst: ~/.config/wallust
  d_scripts:
    src: config/scripts
    dst: ~/.config/scripts
  d_fonts:
    src: fonts
    dst: ~/.fonts
  f_vesktop.css:
    src: config/wallust/templates/vesktop.css
    dst: ~/.config/wallust/templates/vesktop.css
  f_hyprland.lua:
    src: config/hypr/hyprland.lua
    dst: ~/.config/hypr/hyprland.lua
  f_colors.conf:
    src: config/kitty/colors.conf
    dst: ~/.config/kitty/colors.conf
  f_kitty.conf:
    src: config/kitty/kitty.conf
    dst: ~/.config/kitty/kitty.conf
  f_hyprsunset.conf:
    src: config/hypr/hyprsunset.conf
    dst: ~/.config/hypr/hyprsunset.conf
  f_hyprpaper.conf:
    src: config/hypr/hyprpaper.conf
    dst: ~/.config/hypr/hyprpaper.conf
  d_bin:
    src: local/bin
    dst: ~/.local/bin
profiles:
  xBit:
    dotfiles:
    - d_alacritty
    - d_waybar
    - d_dunst
    - d_hypr
    - d_wallust
    - d_scripts
    - d_fonts
    - f_vesktop.css
    - f_hyprland.lua
    - f_colors.conf
    - f_kitty.conf
    - f_hyprsunset.conf
    - f_hyprpaper.conf
    - d_bin
