#!/bin/bash

user=`whoami`

NOTES_PATH="/home/$user/Documents/obsidian/tasks/Daily Notes/"
AVAILABLE_PERIOD=7 # number of days after which daily notes will be deleted.

notify-send "Deleting old notes..." "Deleting notes over $AVAILABLE_PERIOD days old..."

MAX_PERIOD=`date -d "$AVAILABLE_PERIOD days ago"`

# deletes files over 7 days old.
find "$NOTES_PATH" -type f -not -newermt "$MAX_PERIOD" -exec rm {} \;
