#!/bin/sh

#                            _                 _                 _       _   
#  _ __ ___  _   _   _ __ ___| | ___   __ _  __| |  ___  ___ _ __(_)_ __ | |_ 
# | '_ ` _ \| | | | | '__/ _ \ |/ _ \ / _` |/ _` | / __|/ __| '__| | '_ \| __|
# | | | | | | |_| | | | |  __/ | (_) | (_| | (_| | \__ \ (__| |  | | |_) | |_ 
# |_| |_| |_|\__, | |_|  \___|_|\___/ \__,_|\__,_| |___/\___|_|  |_| .__/ \__|
#           |___/                                                 |_|        


reloadStuff=()

for i in ${reloadStuff[@]}; do
    if [ ! $(pidof $i) ]; then
        eval "$i" # executes command.
    fi
done

# a few special cases.
agsv1 -q && agsv1

notify-send -a "Computer" "Reload" "Reloaded configuration successfully!"

