#!/bin/bash

# TODO: implement feature to prevent same background from being set twice, preferably through a global variable

USER=`whoami`

WALLPAPER_PATH="/home/$USER/backgrounds/"

# all files.
wallpapers=($(find $WALLPAPER_PATH -type f -exec realpath -s {} \;))
len=${#wallpapers[@]}

rand=`shuf -i0-$(( $len - 1 )) -n1`
selected="${wallpapers[$rand]}"

notify-send "Picking a new wallpaper..." "Check it out!"
/usr/bin/agsv1 -r "setWallpaper(\"$selected\")"


