#!/bin/bash

count=$(yay -Qu | wc -l)

if [[ $count -gt 0 ]]; then
    confirm=`notify-send -a "computer" "Attention!" "Got $count updates ready!" -A "Y"="Update!" -A "Later" -t 2500000`

    if [[ $confirm -eq "Y" ]]; then
        eval `/usr/bin/alacritty -e "yay"`
    fi
fi
