backend = "full"
color_space = "lab-mixed"
palette = "saliencedark"
check_contrast = true


[templates]
hyprland = { src = "hypr_colors.conf", dst = "~/.config/hypr/colors.conf" }
waybar = { src = "waybar.css", dst = "~/.config/waybar/colors.css" }
pywal_json = { src = "colors.json", dst = "~/.cache/wal/colors.json" }
pywal_sh = { src = "colors.sh", dst = "~/.cache/wal/colors.sh" }
alacritty = { src = "alacritty.toml", dst = "~/.config/alacritty/colors.toml" }
pywal_compat = { src = "pywal.json", dst = "~/.cache/wal/colors.json" }
dunst = { src = "dunstrc", dst = "~/.config/dunst/dunstrc" }
obsidian = { src = "obsidian.css", dst = "~/MyVault/.obsidian/snippets/wallust-colors.css" }
vesktop = { src = "vesktop.css", dst = "~/.config/vesktop/themes/wallust.theme.css" }
waybar_cfg = { src = "waybar.jsonc", dst = "~/.config/waybar/config.jsonc" }
zed = { src = "zed.json", dst = "~/.config/zed/themes/wallust.json" }


[hooks]
on_update = '$HOME/.config/scripts/wallust_on_update'
