$background = rgb(000103)
$foreground = rgb(E1EDFF)
$color0 = rgb(000104)
$color1 = rgb(4A4849)
$color2 = rgb(6A6A6B)
$color3 = rgb(4A5679)
$color4 = rgb(767878)
$color5 = rgb(787576)
$color6 = rgb(C9D5E9)
$color7 = rgb(DBE8FD)
$color8 = rgb(8B96A9)
$color9 = rgb(4A4849)
$color10 = rgb(6A6A6B)
$color11 = rgb(4A5679)
$color12 = rgb(767878)
$color13 = rgb(787576)
$color14 = rgb(C9D5E9)
$color15 = rgb(E5EBF5)
