$background = rgb(030305)
$foreground = rgb(FFC37E)
$color0 = rgb(040608)
$color1 = rgb(434858)
$color2 = rgb(7F7871)
$color3 = rgb(5B7E9E)
$color4 = rgb(8A9075)
$color5 = rgb(A78A93)
$color6 = rgb(E39554)
$color7 = rgb(FFB873)
$color8 = rgb(BB7436)
$color9 = rgb(434858)
$color10 = rgb(7F7871)
$color11 = rgb(5B7E9E)
$color12 = rgb(8A9075)
$color13 = rgb(A78A93)
$color14 = rgb(E39554)
$color15 = rgb(F7D3B1)

$accent = rgb(7F7871)
$selection = rgb(434858)
