# Gerado dinamicamente pelo Wallust
foreground            #BF8495
background            #170D0E
selection_foreground  #170D0E
selection_background  #BF8495

cursor                #BF8495
cursor_text_color     #170D0E

# Cores normais (0 a 7)
color0                #240000
color1                #944F6D
color2                #5C3E43
color3                #743F48
color4                #7B4B58
color5                #C0465D
color6                #674853
color7                #9F6778

# Cores brilhantes (8 a 15)
color8                #744252
color9                #944F6D
color10               #5C3E43
color11               #743F48
color12               #7B4B58
color13               #C0465D
color14               #674853
color15               #C6ABB3
