# Importa as cores geradas pelo Wallust
source = ~/.config/hypr/wallust_colors.conf

general {
    terminal = alacritty
    monitor =
}

background_color = $bg
text_color = $fg
accent_color = $accent
selection_color = $selection
border_color = $accent

# Opções de layout
border_size = 2
corner_radius = 12
icon_size = 48
